import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Testes do Isaque",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-slate-50`}
      >
        <header className="border-b border-slate-800">
          <nav className="max-w-4xl mx-auto flex items-center justify-between px-4 py-3">
            <span className="font-bold">Plataforma Fullstack </span>
            <div className="flex gap-4 text-sm">
              <Link href="/">Home</Link>
              <Link href="/tasks">Tarefas</Link>
              <Link href="/about">Sobre</Link>
            </div>
          </nav>
        </header>
        <main className="max-w-4xl mx-auto px-4 py-8 ">{children}</main>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
